set serveroutput on size unlimited;

-- Tạo user ADMIN2 trong SQL Plus
--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--CREATE USER ADMIN2 IDENTIFIED BY 123; 
--GRANT DBA TO ADMIN2; 
--GRANT EXECUTE ANY PROCEDURE TO ADMIN2; 
--GRANT CREATE SESSION TO ADMIN2 CONTAINER = ALL; 

-- Xóa user ADMIN2 trong SQL Plus
--alter session set "_ORACLE_SCRIPT" = TRUE;
--DROP USER ADMIN2 CASCADE;

-- Connect đến ADMIN2 để tạo bảng
--DROP TABLE ADMIN2.CHITIETTHANHTOAN;
--DROP TABLE ADMIN2.CHUNGNHAN;
--DROP TABLE ADMIN2.CHINHSACH;
--DROP TABLE ADMIN2.PHIEUTHANHTOAN;
--DROP TABLE ADMIN2.DANGTUYEN;
--DROP TABLE ADMIN2.HOSOUNGTUYEN;
--DROP TABLE ADMIN2.NHANVIEN;
--DROP TABLE ADMIN2.UNGVIEN;
--DROP TABLE ADMIN2.DOANHNGHIEP;

CREATE TABLE ADMIN2.DOANHNGHIEP (
  MaDoanhNghiep VARCHAR(5),
  TenCongTy VARCHAR2(50),
  DiaChi VARCHAR2(50),
  Email VARCHAR2(50),
  MaSoThue VARCHAR(20),
  NgayDangKy DATE,
  NguoiDaiDien VARCHAR2(50),
  TrangThai VARCHAR2(50),
  PRIMARY KEY(MaDoanhNghiep)
);
CREATE TABLE ADMIN2.NHANVIEN (
  MaNhanVien VARCHAR(5),
  TenNhanVien VARCHAR2(50),
  ChucVu VARCHAR2(50),
  DiaChi VARCHAR2(50),
  Luong INT,
  SDT VARCHAR(10),
  PRIMARY KEY(MaNhanVien)
);

CREATE TABLE ADMIN2.UNGVIEN (
  MaUngVien VARCHAR(5),
  TenUngVien VARCHAR2(50),
  NgaySinh DATE,
  GioiTinh VARCHAR2(10),
  CCCD VARCHAR(15),
  SDT VARCHAR(10),
  DiaChi VARCHAR2(50),
  PRIMARY KEY(MaUngVien)
);

CREATE TABLE ADMIN2.DANGTUYEN (
  MaDangTuyen VARCHAR(5),
  MaDoanhNghiep VARCHAR(5),
  HinhThucDangTuyen VARCHAR2(50),
  NgayLap DATE,
  NgayDangTuyen DATE,
  ThoiHan INT,
  ViTriUngTuyen VARCHAR2(50),
  SoLuong INT,
  YeuCauChoUngVien VARCHAR2(200),
  TrangThai VARCHAR2(50), -- 'đang đăng tuyển'
  LinkDangBai VARCHAR2(500),
  PRIMARY KEY(MaDangTuyen)
);

CREATE TABLE ADMIN2.CHINHSACH(
  MaChinhSach VARCHAR(5),
  Ten VARCHAR2(50),
  MoTa VARCHAR(100),
  TrangThai VARCHAR2(50),
  PRIMARY KEY(MaChinhSach)
);
CREATE TABLE ADMIN2.PHIEUTHANHTOAN (
  MaPhieuThanhToan VARCHAR(5),
  MaDangTuyen VARCHAR(5),
  TongTien INT,
  TienDaTra INT,
  LoaiThanhToan VARCHAR2(50),
  PRIMARY KEY(MaPhieuThanhToan)
);
CREATE TABLE ADMIN2.CHITIETTHANHTOAN (
  MaPhieuThanhToan VARCHAR(5),
  Dot INT,
  SoTien INT, 
  HinhThucThanhToan VARCHAR2(50),
  NhanVienThanhToan VARCHAR(5),
  ThoiGian DATE,
  PRIMARY KEY(MaPhieuThanhToan, Dot)
);

CREATE TABLE ADMIN2.HOSOUNGTUYEN (
  MaHoSo VARCHAR(5),
  MaUngVien VARCHAR(5),
  MaDangTuyen VARCHAR(5),
  TrangThaiHoSo VARCHAR2(50),
  ViTriUngTuyen VARCHAR2(50),
  DoUuTien INT,
  NhanVienDuyet VARCHAR(5),
  NgayLap DATE,
  ThoiGianDuyet INT,
  PRIMARY KEY(MaHoSo)
);

CREATE TABLE ADMIN2.CHUNGNHAN (
  MaUngVien VARCHAR(5),
  ID VARCHAR(5),
  TenChungNhan VARCHAR2(50),
  ChuyenNganh VARCHAR2(50),
  LoaiBang VARCHAR2(50),
  NgayCap DATE,
  NgayHetHan DATE,
  ToChucCap VARCHAR2(50),
  PRIMARY KEY(ID)
);

-- DROP FK
--ALTER TABLE DANGTUYEN DROP CONSTRAINT FK_DANGTUYEN_DOANHNGHIEP;
--ALTER TABLE PHIEUTHANHTOAN DROP CONSTRAINT FK_PHIEUTHANHTOAN_DANGTUYEN;
--ALTER TABLE CHITIETTHANHTOAN DROP CONSTRAINT FK_CHITIETTHANHTOAN_PHIEUTHANHTOAN;
--ALTER TABLE CHITIETTHANHTOAN DROP CONSTRAINT FK_CHITIETTHANHTOAN_NHANVIEN;
--ALTER TABLE HOSOUNGTUYEN DROP CONSTRAINT FK_HOSOUNGTUYEN_NHANVIEN;
--ALTER TABLE HOSOUNGTUYEN DROP CONSTRAINT FK_HOSOUNGTUYEN_UNGVIEN;
--ALTER TABLE CHUNGNHAN DROP CONSTRAINT FK_CHUNGNHAN_UNGVIEN;

-- CREATE  FK

--MaDoanhNghiep trong DANGTUYEN
ALTER TABLE ADMIN2.DANGTUYEN
ADD
    CONSTRAINT FK_DANGTUYEN_DOANHNGHIEP
    FOREIGN KEY (MaDoanhNghiep)
    REFERENCES ADMIN2.DOANHNGHIEP;
--MaDangTuyen trong PHIEUTHANHTOAN
ALTER TABLE ADMIN2.PHIEUTHANHTOAN
ADD
    CONSTRAINT FK_PHIEUTHANHTOAN_DANGTUYEN
    FOREIGN KEY (MaDangTuyen)
    REFERENCES ADMIN2.DANGTUYEN;
--MaPhieuThanhToan trong CHITIETTHANHTOAN
ALTER TABLE ADMIN2.CHITIETTHANHTOAN
ADD
    CONSTRAINT FK_CHITIETTHANHTOAN_PHIEUTHANHTOAN
    FOREIGN KEY (MaPhieuThanhToan)
    REFERENCES ADMIN2.PHIEUTHANHTOAN;
--NhanVienThanhToan trong CHITIETTHANHTOAN
ALTER TABLE ADMIN2.CHITIETTHANHTOAN
ADD
    CONSTRAINT FK_CHITIETTHANHTOAN_NHANVIEN
    FOREIGN KEY (NhanVienThanhToan)
    REFERENCES ADMIN2.NHANVIEN;
--NhanVienDuyet trong HOSOUNGTUYEN
ALTER TABLE ADMIN2.HOSOUNGTUYEN
ADD
    CONSTRAINT FK_HOSOUNGTUYEN_NHANVIEN
    FOREIGN KEY (NhanVienDuyet)
    REFERENCES ADMIN2.NHANVIEN;
--MaUngVien trong HOSOUNGTUYEN
ALTER TABLE ADMIN2.HOSOUNGTUYEN
ADD
    CONSTRAINT FK_HOSOUNGTUYEN_UNGVIEN
    FOREIGN KEY (MaUngVien)
    REFERENCES ADMIN2.UNGVIEN;
--MaUngVien trong CHUNGNHAN
ALTER TABLE ADMIN2.CHUNGNHAN
ADD
    CONSTRAINT FK_CHUNGNHAN_UNGVIEN
    FOREIGN KEY (MaUngVien)
    REFERENCES ADMIN2.UNGVIEN;
--MaDangTuyen trong HOSOUNGTUYEN
ALTER TABLE ADMIN2.HOSOUNGTUYEN
ADD
    CONSTRAINT FK_HOSOUNGTUYEN_DANGTUYEN
    FOREIGN KEY (MaDangTuyen)
    REFERENCES ADMIN2.DANGTUYEN;    
-- constraint
ALTER TABLE admin2.dangtuyen
--drop CONSTRAINT check_HinhThucDangTuyen
ADD CONSTRAINT check_HinhThucDangTuyen CHECK (HinhThucDangTuyen IN ('Banner', 'Social media', 'Báo giấy'));

ALTER TABLE admin2.DANGTUYEN
--drop CONSTRAINT check_TrangThai_dangtuyen
ADD CONSTRAINT check_TrangThai_dangtuyen CHECK (TrangThai IN ('Chưa Đăng Tuyển', 'Đang đăng tuyển', 'Hết hạn'));
    
-- Dữ liệu
INSERT INTO ADMIN2.DOANHNGHIEP VALUES('DN001', 'Công Ty A', 'Hồ Chí Minh','congtyA@gmail.com','123456789101112', TO_DATE('01-01-2024','DD-MM-YYYY'), 'Nguyễn Văn A', 'Doanh nghiệp tiềm năng');
INSERT INTO ADMIN2.DOANHNGHIEP VALUES('DN002', 'Công Ty B', 'Hồ Chí Minh','congtyB@gmail.com','123456789101113', TO_DATE('01-01-2024','DD-MM-YYYY'), 'Nguyễn Văn B', 'Doanh nghiệp tiềm năng lớn');
INSERT INTO ADMIN2.DOANHNGHIEP VALUES('DN003', 'Công Ty C', 'Hồ Chí Minh','congtyC@gmail.com','123456789101114', TO_DATE('01-01-2024','DD-MM-YYYY'), 'Nguyễn Văn C', 'Không');

INSERT INTO ADMIN2.NHANVIEN VALUES('NV001', 'Nguyễn Thị Hương', 'nhân viên','Hồ Chí Minh', 10000000, '0211112222');
INSERT INTO ADMIN2.NHANVIEN VALUES('NV002', 'Lê Thị Thu', 'nhân viên','Hồ Chí Minh', 10000000, '0233334444');
INSERT INTO ADMIN2.NHANVIEN VALUES('NV003', 'Phạm Đức Anh', 'nhân viên','Hồ Chí Minh', 10000000, '0266669999');
INSERT INTO ADMIN2.NHANVIEN VALUES('LD001', 'Lại Chí Thiện', 'ban lãnh đạo','Hồ Chí Minh', 10000000, '0266669999');

INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV004', 'Nguyen Van A', 'nhân viên tiếp tân', '123 Đường A, Quận 1', 5000000, '0901234567');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV005', 'Tran Thi B', 'nhân viên tiếp tân', '456 Đường B, Quận 2', 5200000, '0912345678');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV006', 'Le Van C', 'nhân viên tiếp tân', '789 Đường C, Quận 3', 5400000, '0923456789');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV007', 'Pham Thi D', 'nhân viên tiếp tân', '321 Đường D, Quận 4', 5600000, '0934567890');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV008', 'Hoang Van E', 'nhân viên tiếp tân', '654 Đường E, Quận 5', 5800000, '0945678901');

INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV009', 'Nguyen Van F', 'Nhân viên quảng cáo', '123 Đường F, Quận 6', 6000000, '0951234567');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV010', 'Tran Thi G', 'Nhân viên quảng cáo', '456 Đường G, Quận 7', 6200000, '0962345678');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV011', 'Le Van H', 'Nhân viên quảng cáo', '789 Đường H, Quận 8', 6400000, '0973456789');
INSERT INTO ADMIN2.NHANVIEN (MaNhanVien, TenNhanVien, ChucVu, DiaChi, Luong, SDT) VALUES ('NV012', 'Pham Thi I', 'Nhân viên quảng cáo', '321 Đường I, Quận 9', 6600000, '0984567890');


INSERT INTO ADMIN2.UNGVIEN VALUES('UV001', 'Trần Văn Minh',TO_DATE('01-01-2000','DD-MM-YYYY'),'Nam','010203040506','0212345678', 'Hồ Chí Minh');
INSERT INTO ADMIN2.UNGVIEN VALUES('UV002', 'Hoàng Thị Lan',TO_DATE('01-01-2000','DD-MM-YYYY'),'Nữ','010203040506','0298765432', 'Hồ Chí Minh');
INSERT INTO ADMIN2.UNGVIEN VALUES('UV003', 'Vũ Quang Huy',TO_DATE('01-01-2000','DD-MM-YYYY'),'Nam','010203040506','0255558888', 'Hồ Chí Minh');

INSERT INTO ADMIN2.DANGTUYEN VALUES('DT001', 'DN001', 'Banner', TO_DATE('01-01-2024','DD-MM-YYYY'), TO_DATE('10-01-2024','DD-MM-YYYY'), 60, 'Lập trình viên', 2, '1 năm kinh nghiệm', NULL, NULL);
INSERT INTO ADMIN2.DANGTUYEN VALUES('DT002', 'DN002', 'Banner', TO_DATE('01-01-2024','DD-MM-YYYY'), TO_DATE('10-01-2024','DD-MM-YYYY'), 60, 'Lập trình viên', 2, '1 năm kinh nghiệm', NULL, NULL);
INSERT INTO ADMIN2.DANGTUYEN VALUES('DT003', 'DN003', 'Banner', TO_DATE('01-01-2024','DD-MM-YYYY'), TO_DATE('10-01-2024','DD-MM-YYYY'), 60, 'Lập trình viên', 2, '1 năm kinh nghiệm', NULL, NULL);

INSERT INTO ADMIN2.CHINHSACH VALUES('CS001', 'Quà tặng','Tặng 1 phần quà lưu niệm', 'Hoạt động');
INSERT INTO ADMIN2.CHINHSACH VALUES('CS002', 'Giảm giá','Giảm giá phí đăng tuyển 5%', 'Không hoạt động');
INSERT INTO ADMIN2.CHINHSACH VALUES('CS003', 'Tri ân cuối năm','Tặng 1 phần quà vào cuối năm', 'Hoạt động');
INSERT INTO ADMIN2.CHINHSACH VALUES('CS004', 'Quà sinh nhật','Tặng 1 phần quà vào dịp sinh nhật', 'Không hoạt động');

INSERT INTO ADMIN2.PHIEUTHANHTOAN VALUES('TT001', 'DT001', 5000000, 0, 'Trả góp');

INSERT INTO ADMIN2.CHITIETTHANHTOAN VALUES('TT001', 1, 5000000, 'tiền mặt', 'NV001', TO_DATE('01-01-2024','DD-MM-YYYY'));

INSERT INTO ADMIN2.HOSOUNGTUYEN VALUES('HS001', 'UV001', 'DT001','đang duyệt','lập trình viên', 0 ,'NV001', TO_DATE('01-01-2024','DD-MM-YYYY'), 3);

INSERT INTO ADMIN2.CHUNGNHAN VALUES('UV001', 'CN001', 'Bằng tiếng Anh','Ngôn ngữ Anh','Giỏi', TO_DATE('01-01-2024','DD-MM-YYYY'), TO_DATE('01-01-2026','DD-MM-YYYY'), 'IIG');

update ADMIN2.Dangtuyen set hinhthucdangtuyen = 'Banner';



SELECT * FROM ADMIN2.DOANHNGHIEP;
SELECT * FROM ADMIN2.PHIEUTHANHTOAN;
SELECT * FROM ADMIN2.CHITIETTHANHTOAN;
SELECT * FROM ADMIN2.DANGTUYEN;
SELECT * FROM ADMIN2.NHANVIEN;
SELECT * FROM ADMIN2.HOSOUNGTUYEN;
SELECT * FROM ADMIN2.UNGVIEN;
SELECT * FROM ADMIN2.CHUNGNHAN;
SELECT * FROM ADMIN2.CHINHSACH;
